services:
  backend:
    build: ./mern/backend     #this is a folder where the dockerfile is located
    ports:
      - "5051:5050" 
    networks:
      - networkmern
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  
    depends_on:
      - mongodb

  frontend:
    build: ./mern/frontend     #this is a folder where the dockerfile is located
    ports:
      - "5174:5173"  
    networks:
      - networkmern
    environment:
      REACT_APP_API_URL: http://backend:5050 

  mongodb:
    image: mongo:latest  
    ports:
      - "27018:27017"  
    networks:
      - networkmern
    volumes:
      - mongo-data:/data/db  

networks:
  networkmern:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally

